"""Effect Activity bridge to the shared arbitration Strands/A2A fixtures.

The subprocess boundary is product-owned trial code. A receiver lookup is a
fixture-specific contract, not an A2A guarantee.
"""
from __future__ import annotations

import json
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
OLD = HERE.parents[1] / "2026-09-22"
sys.path.insert(0, str(OLD / "decision-round" / "common"))
import client  # noqa: E402
sys.path.insert(0, str(OLD / "arbitration" / "common"))
import fixture  # noqa: E402
import receiver_client  # noqa: E402
import definition  # noqa: E402


def health(url: str, identity: str, role: str) -> None:
    with urllib.request.urlopen(url.rstrip("/") + "/health", timeout=3) as response:
        observed = json.load(response)
    if observed.get("identity") != identity or observed.get("role", observed.get("mode")) != role:
        raise ValueError("pinned service identity/role mismatch")


def existing(url: str, command: dict) -> dict | None:
    try:
        return client.reconcile(url, command["action_id"], command["run_id"],
                                command["definition_digest"])
    except RuntimeError as error:
        if str(error).startswith("HTTP 404:"):
            return None
        raise


def verified_task(url: str, binding: dict, command: dict, receipt: dict) -> dict:
    role = binding["role"]
    task = client.get_task(url, receipt["task_id"])
    metadata = task.get("metadata") or {}
    if task.get("id") != receipt["task_id"] or task.get("status", {}).get("state") != "completed":
        raise ValueError("A2A Task is not completed with the recorded ID")
    for key in ("action_id", "run_id", "definition_digest"):
        if receipt.get(key) != command[key] or metadata.get(key) != command[key]:
            raise ValueError("A2A Task and receipt binding mismatch: " + key)
    if metadata.get("harness_identity") != binding["identity"] or metadata.get("harness_role") != role:
        raise ValueError("A2A Task service identity/role mismatch")
    if receipt.get("role") != role or task.get("artifacts", [{}])[0].get("artifactId") != receipt["artifact"]["sha256"]:
        # Quality verdicts do not have a content digest; their A2A artifact ID
        # is generated by the shared harness. The role check still applies.
        if role != "quality" or receipt.get("role") != role:
            raise ValueError("A2A Task artifact/role mismatch")
    return {"task_id": receipt["task_id"], "artifact": receipt["artifact"],
            "receiver_attempts": receipt["attempts"],
            "receiver_effects": receipt["accepted_count"],
            "service_identity": binding["identity"]}


def invoke(binding: dict, command: dict) -> dict:
    url = binding["url"]
    health(url, binding["identity"], binding["role"])
    receipt = existing(url, command)
    if receipt is None:
        try:
            client.send(url, command)
        except client.UncertainSubmission:
            # The participating receiver may have committed and exited before
            # replying. Allow the trial supervisor time to restart it.
            pass
        deadline = time.monotonic() + 25
        while receipt is None and time.monotonic() < deadline:
            try:
                receipt = existing(url, command)
            except (urllib.error.URLError, client.UncertainSubmission):
                pass
            if receipt is None:
                time.sleep(.2)
        if receipt is None:
            raise RuntimeError("remote action unresolved; no blind resubmit")
    return verified_task(url, binding, command, receipt)


def run(op: str, data: dict) -> dict:
    if op == "validate":
        return {"digest": definition.validate(data["package"], data["approved_bindings"])}
    if op == "assign":
        command = fixture.assignment(data["run"], data["digest"], data["instance"],
                                     result_type=data["result_type"],
                                     scope_status=data["scope_status"],
                                     drop_ack=data.get("drop_ack", False))
        result = invoke(data["binding"], command)
        if result["artifact"].get("author") != data["binding"]["identity"]:
            raise ValueError("assignment artifact author mismatch")
        return result
    if op == "join":
        receipts = {name: {"action_id": f"{data['run']}:{name}",
                           "run_id": data["run"], "definition_digest": data["digest"],
                           "artifact": item["artifact"]}
                    for name, item in data["branches"].items()}
        return fixture.typed_join(receipts, run_id=data["run"],
                                  definition_digest=data["digest"],
                                  declarations=data["declarations"],
                                  scope_status_by_instance=data["scopes"])
    if op == "synthesize":
        return fixture.candidate_artifact(data["join"], data["revision"],
                                          data["author"], resolved=data["resolved"])
    if op == "review":
        candidate = data["artifact"]
        command = {"op": "review", "action_id": f"{data['run']}:quality:{candidate['revision']}",
                   "run_id": data["run"], "definition_digest": data["digest"],
                   "artifact": candidate}
        result = invoke(data["binding"], command)
        verdict = result["artifact"]
        if (verdict.get("reviewer") != data["binding"]["identity"]
                or verdict.get("reviewer") == candidate["author"]
                or verdict.get("revision") != candidate["revision"]
                or verdict.get("sha256") != candidate["sha256"]
                or type(verdict.get("accepted")) is not bool):
            raise ValueError("Quality verdict does not bind current independent candidate")
        return result
    if op == "release":
        command = data["command"]
        binding = data["binding"]
        health(binding["url"], binding["identity"], "participating")
        try:
            result = receiver_client.receipt(binding["url"], command["release_id"])
        except RuntimeError as error:
            if not str(error).startswith("HTTP 404:"):
                raise
            result = None
        if result is None:
            try:
                result = receiver_client.release(binding["url"], command)
            except receiver_client.UncertainDelivery:
                deadline = time.monotonic() + 25
                while result is None and time.monotonic() < deadline:
                    try:
                        result = receiver_client.receipt(binding["url"], command["release_id"])
                    except (receiver_client.UncertainDelivery, urllib.error.URLError):
                        pass
                    except RuntimeError as error:
                        if not str(error).startswith("HTTP 404:"):
                            raise
                    if result is None:
                        time.sleep(.2)
                if result is None:
                    raise RuntimeError("release unresolved; no blind resubmit")
        for key in ("release_id", "run_id", "definition_digest", "revision", "sha256"):
            if result.get(key) != command[key]:
                raise ValueError("release receipt binding mismatch: " + key)
        return result
    raise ValueError("unknown bridge operation")


if __name__ == "__main__":
    try:
        print(json.dumps(run(sys.argv[1], json.load(sys.stdin)), sort_keys=True))
    except Exception as error:
        print(f"{type(error).__name__}: {error}", file=sys.stderr)
        raise SystemExit(1)
